sudo: required
dist: trusty
language: java

jdk:
  - oraclejdk8

before_install:
    ## Download the SourceClear agent deb package and install
    - curl -sSL https://download.sourceclear.com/ci.sh | bash | awk 'BEGIN {code = 1} {print $0} /SourceClear found no component data|0 vulnerable libraries/ {code = 0} END {exit code}'
