sudo: required
dist: trusty
language: java

jdk:
  - oraclejdk8

before_install:
    ## Download the SourceClear agent deb package and install
    - curl -sSL https://download.sourceclear.com/ci.sh | bash | grep -F -q -e '0 vulnerable libraries' || exit(1)
